on:
  push:

defaults:
  run:
    shell: bash

jobs:
  python-artifact:
    runs-on: ubuntu-latest
    name: "python artifact"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build
      run: |
        docker build -t python-artifact-demo .

    -name: Deploy


