on:
  push:

defaults:
  run:
    shell: bash

jobs:
  python-artifact:
    runs-on: ubuntu-latest
    name: "python artifact"

    env:
      CR_PAT: ${{ secrets.CR.PAT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build
      run: |
        docker build -t python-artifact-demo:latest .
        docker tag python-artifact-demo:latest ghcr.io/chaoslecion123/cicd-artifact-python/python-artifact-demo:latest

    - name: Deploy
      run: |
        echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        docker push ghcr.io/chaoslecion123/cicd-artifact-python/python-artifact-demo:lates


